### ISSUE TITLE
Deployment fails after upgrading secrecy from 0.8 to 0.10.3 - SHUTTLE_API_KEY not being read

### ISSUE THREAD

**Issue by reddevilmidzy** [shuttle-hq/shuttle#2066]
### What happened?

This is my shuttle_deploy.yml file.

<details>
  <summary><a href="https://github.com/reddevilmidzy/queensac/blob/main/.github/workflows/shuttle_deploy.yml">shuttle_deploy.yml</summary>
<p>

```
name: Shuttle Deploy

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          working-directory: rook
```

</p>
</details>

After upgrading the secrecy version in Cargo.toml from 0.8 to 0.10.3, the deployment is failing.
Looking at the [action logs](https://github.com/reddevilmidzy/queensac/actions/runs/15838312209/job/44650374161), it appears that SHUTTLE_API_KEY is not being read properly during the `Run shuttle deploy --id` step. (error: a value is required for '--name <NAME_OR_ID>' but none was supplied)
However, when I [redeployed](https://github.com/reddevilmidzy/queensac/actions/runs/15836814550) with secrecy version 0.8, it succeeded, which indicates that SHUTTLE_API_KEY is properly configured.

### Version

v0.54.0

### Which operating system(s) are you seeing the problem on?

Windows

### Relevant log output

```sh

```

### Duplicate declaration

- [x] I have searched the issues and there are none like this.
