### ISSUE TITLE
Deploy crashed after updating to 0.11.0

### ISSUE THREAD

**Issue by Schoude** [shuttle-hq/shuttle#659]
After updating my project to version 0.11.0 following the given steps fromt the [release notes](https://github.com/shuttle-hq/shuttle/releases/tag/v0.11.0) this error the not found package `strfmt` pops up in the logs when I try to run `cargo shuttle deploy`

```sh
{error="Build error: no matching package named `strfmt` found\nlocation searched: registry `crates-io`\nrequired by package `shuttle-service v0.11.0 (/usr/src/shuttle/service)`\n    ... which satisfies dependency `shuttle-service = \"^0.11.0\"` (locked to 0.11.0) of package `my-package-name-0a05dc5a-9fda-4e87-984c-cd38ad390c3a v0.1.0 (/opt/shuttle/shuttle-builds/my-package-name)`"} shuttle_deployer::deployment::queue: service build encountered an error
```

Running the shuttle service locally with `cargo shuttle run` worked but the compile time was about 5 minutes. I am running all this stuff in WSL with Ubungu on Windows 10 so this might also be an issue,

This is my `Cargo.toml` file

```toml
[package]
name = "my-project-name"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
axum = "0.6.6"
tokio = { version = "1.22.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
reqwest = { version = "0.11.14", features = ["json"] }
thiserror = "1.0.38"
url = "2.3.1"
sync_wrapper = "0.1.2"
shuttle-service = { version = "0.11.0", features = ["web-axum"] }
shuttle-secrets = "0.11.0"
tower-http = { version = "0.4.0", features = ["cors"] }
tower = "0.4.13"
```
