### ISSUE TITLE
[Feature]: Support for choosing binary target

### ISSUE THREAD

**Issue by akhildevelops** [shuttle-hq/shuttle#751]
### Describe the feature

It would be helpful to have an option like `cargo shuttle deploy --bin <bin_name>` similar to running a specific binary target from cargo: `cargo run --bin <bin_name>`.

This will help to write multiple binaries for specific environment. Ex: A specific binary for shuttle environment and another binary that has it's own server.

Ref: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by jonaro00** [comment]
I like it.
This could also be a field in `Shuttle.toml` like
```toml
name = "project"
bin = "shuttle"
```
Where `Cargo.toml` is something like
```toml
[[bin]]
name = "shuttle"

[[bin]]
name = "standalone"
```
